---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai-factory.suse.com
  resources:
  - aijobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai-factory.suse.com
  resources:
  - aijobs/finalizers
  - aiworkloads/finalizers
  - installaiextensions/finalizers
  verbs:
  - update
- apiGroups:
  - ai-factory.suse.com
  resources:
  - aijobs/status
  - aiworkloads/status
  - installaiextensions/status
  - settings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ai-factory.suse.com
  resources:
  - aiworkloads
  - blueprints
  - installaiextensions
  - settings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai-factory.suse.com
  resources:
  - blueprintcatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fleet.cattle.io
  resources:
  - bundledeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleet.cattle.io
  resources:
  - bundles
  - gitrepos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.cattle.io
  resources:
  - helmops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - clusterqueues
  - localqueues
  verbs:
  - get
  - list
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - workloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - resource.k8s.io
  resources:
  - deviceclasses
  - resourceslices
  verbs:
  - get
  - list
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaimtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.nvidia.com
  resources:
  - computedomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.run.ai
  resources:
  - queues
  verbs:
  - get
  - list
